# https://github.com/gautamkrishnar/blog-post-workflow
name: Update blog posts

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

permissions:
  contents: write

jobs:
  update-blog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://blog.ooooo.space/feed.xml"
          max_post_count: "6"
          template: "- [$title]($url) — $date$newline"
          date_format: "yyyy-mm-dd"
          comment_tag_name: "BLOG-POST-LIST"
          tag_post_pre_newline: "true"
